home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name="home"),

]

restbank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('portfolio/', include('portfolio.urls')),
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    path("create/", views.CreateUserView.as_view(), name="create"),
    path("authenticate/", views.CreateTokenView.as_view(), name="authenticate"),
    path("my-account/", views.ManageUserView.as_view(), name="my-account"),
    path("current-user/", views.CurrentUserApiView.as_view(), name="current-user"),
]

home/views.py
from django.shortcuts import render


def home(request):
    return render(request, "home.html")

templates/home.html
<!DOCTYPE html>
{% load staticfiles %} {% load bootstrap_tags %}
<html>

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0">
    <title>RESTBank</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Materialize-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- FontAwesome Styles-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css"
          integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <!-- Custom Styles-->
    <link href="{% static 'css/landing-page.css' %}" rel="stylesheet"/>
    <!-- jQuery-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Chart Js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
    <!-- Material Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% block extrahead %}{% endblock %}
    {% block head_js %}
    {% endblock head_js %}
    <style>
      @font-face {
        font-family: 'Source Sans Pro';
        font-weight: 400 500;
        src: url('{% static 'fonts/TTF/SourceSansPro-Regular.ttf' %}');
      }
      @font-face {
        font-family: 'Source Sans Pro';
        font-weight: bold 600;
        src: url('{% static 'fonts/TTF/SourceSansPro-Semibold.ttf' %}');
      }
      @font-face {
        font-family: 'Raleway';
        src: url('{% static 'fonts/TTF/Raleway-Regular.ttf' %}');
      }

    </style>

</head>

<body>
<!-- TOP NAVBAR -->
<nav class="navbar navbar-default top-navbar" role="navigation">
    <div class="navbar-header">
        <a class="navbar-brand waves-effect waves-dark" href="{% url 'home' %}"> <img
                src="{% static 'img/restbank.png' %}" class="responsive logo-img"></a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
        <li><a class="dropdown-button waves-effect waves-dark" target="_blank"
               href="https://github.com/LukaszMalucha"><i class="fab fa-github" style="color: #24292e;"></i>
            <b>GitHub</b></a></li>
        <li><a class="dropdown-button waves-effect waves-dark" target="_blank"
               href="https://www.linkedin.com/in/lukaszmalucha"><i class="fab fa-linkedin" style="color: #0077b5;"></i>
            <b>Linkedin</b></a></li>
        <li><a class="dropdown-button waves-effect waves-dark" target="_blank"
               href="https://projectgamification.herokuapp.com/"><i class="fas fa-code-branch"
                                                                    style="color: #652960;"></i><b>Portfolio</b></a>
        </li>
    </ul>
</nav>
<!-- PAGE-INDEX -->
<div class="wrapper">
    <div class="row" style=" height:100px"></div>
    <div class="container text-center welcome">
        <div class="row">
            <h3>Welcome to the RESTBank API</h3>
        </div>
        <br>
        <div class="row">

            <div class="col-md-3 text-center">
                <button onclick="window.location='{% url 'user:create' %}'" class="btn route"><b>Register</b></button>
            </div>
            <div class="col-md-3 text-center">
                <button onclick="window.location='{% url 'user:authenticate' %}'" class="btn route"><b>Authenticate</b>
                </button>
            </div>
            <div class="col-md-3 text-center">
                <button onclick="window.location='{% url 'user:my-account' %}'" class="btn route"><b>User Details</b>
                </button>
            </div>
            <div class="col-md-3 text-center">
                <button onclick="window.location='/portfolio/'" class="btn route"><b>My
                    Portfolio</b></button>
            </div>

        </div>
        <br>
    </div>
    <!-- PAGE-INDEX -->

    <!-- JS Scripts-->

    <!-- Bootstrap Js -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <!-- Materialize Js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


    <!-- Custom Js -->
    <script src="{% static 'js/custom-scripts.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
    <script> var csrf_token = '{{ csrf_token }}' </script>

    <script>
        $('.dropdown-trigger').dropdown();

    </script>

</body>

</html>
<ul>
    {% for d in data %}
    <li>Title: {{ d.name }}</li>
    <li>SEO Title:{{ d.ticker }}</li>
    {% endfor %}
</ul>